### ISSUE TITLE
No results for movie suggestions

### ISSUE THREAD

**Issue by ambernay** [francella-toritse-wilson/the-film-factory#26]
We think the message should be more descriptive of the results that aren't available. Like,  "Based on your search: no matching results found."

**Comment by shehsarfraz** [comment]
Also, (just a suggestion piggybacking off this) you could leave the heading "Based on your search, we think you might like these foreign-language films" and then put "no results found" beneath it, that way people know that's what is being referred to with the no results heading. 😊
